name: Bump build version

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and bump version
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Bump build WebApp version
        id: bump-webapp
        uses: vers-one/dotnet-project-version-updater@v1.0
        with:
          file: "src/WebApp/WebApp.csproj"
          version: bump-build

      - name: Bump build Server version
        id: bump-server
        uses: vers-one/dotnet-project-version-updater@v1.0
        with:
          file: "src/Server/Server.csproj"
          version: bump-build

      - name: Bump build Client version
        id: bump-client
        uses: vers-one/dotnet-project-version-updater@v1.0
        with:
          file: "src/Client/Client.csproj"
          version: bump-build

      - run: |
          git config user.name "pushnitsa"
          git config user.email "pushnitsa@users.noreply.github.com"
          git add .
          git commit -m "Bump project version to ${{ steps.bump-webapp.outputs.newVersion }}"
          git push