name: Test passing data through steps

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test passing data
    steps:
      - name: Echo 1
        id: test1
        run: echo "::set-output name=author::${{ github.actor }}"
      - name: Echo 2
        run: echo ${{ steps.test1.outputs.author }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Install dotnet-version
        run: dotnet tool install -g dotnet-version-cli

      - name: Install jq
        run: apt-get install jq

      - name: Get version
        run: |
          cd src/WebApp
          dotnet version --dry-run --output-format=json | jq .currentVersion